# Generated by Django 3.1.7 on 2021-02-24 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('is_buy', models.BooleanField(default=False)),
                ('is_personal', models.BooleanField(default=False)),
                ('journal_ref_id', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('transaction_id', models.BigIntegerField()),
                ('type_id', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=24)),
                ('user', models.ForeignKey(blank=True, help_text='The user to whom this token belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
