# Generated by Django 3.1.7 on 2021-03-11 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mogul_backend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eveuniverse', '0004_effect_longer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(default=0)),
                ('alliance_id', models.IntegerField(null=True)),
                ('corporation_id', models.IntegerField(null=True)),
                ('name', models.CharField(default='Cool Guy', max_length=32, null=True)),
                ('last_esi_pull', models.DateTimeField(default=mogul_backend.models.one_day_ago)),
                ('user', models.ForeignKey(blank=True, help_text='The user to whom this character belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown Structure', max_length=64)),
                ('owner_id', models.IntegerField()),
                ('solar_system_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('position_x', models.FloatField(blank=True, default=None, help_text='x position in the solar system', null=True)),
                ('position_y', models.FloatField(blank=True, default=None, help_text='y position in the solar system', null=True)),
                ('position_z', models.FloatField(blank=True, default=None, help_text='z position in the solar system', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('is_buy', models.BooleanField(default=False, null=True)),
                ('is_personal', models.BooleanField(default=False, null=True)),
                ('journal_ref_id', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('transaction_id', models.BigIntegerField()),
                ('type_id', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=24)),
                ('type_name', models.CharField(default='Unknown', max_length=64)),
                ('station_name', models.CharField(default='Unknown', max_length=64)),
                ('processed', models.BooleanField(default=False)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('stock_date', models.DateTimeField(null=True)),
                ('character_id', models.IntegerField(default=0)),
                ('corporation_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, help_text='The user to whom this transaction belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('station', models.BigIntegerField()),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit_tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax_data', models.JSONField()),
                ('item', models.ForeignKey(help_text='The item involved on this stock row.', null=True, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evetype')),
                ('transaction', models.ForeignKey(help_text='The transaction that created the stock.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_trans_row', to='mogul_backend.transaction')),
                ('user', models.ForeignKey(help_text='The user to whom this stock belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_data', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('station', models.BigIntegerField()),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit_tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax_data', models.JSONField()),
                ('item', models.ForeignKey(help_text='The item involved on this profit row.', null=True, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evetype')),
                ('transaction', models.ForeignKey(help_text='The transaction that created the profit.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_trans_row', to='mogul_backend.transaction')),
                ('user', models.ForeignKey(help_text='The user to whom this profit belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('duration', models.IntegerField()),
                ('is_buy_order', models.BooleanField(null=True)),
                ('is_corporation', models.BooleanField(default=False, null=True)),
                ('issued', models.DateTimeField()),
                ('location_id', models.BigIntegerField()),
                ('min_volume', models.IntegerField(default=0, null=True)),
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('range', models.CharField(default='0', max_length=16)),
                ('region_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('volume_remain', models.IntegerField()),
                ('volume_total', models.IntegerField()),
                ('character_id', models.IntegerField(default=0)),
                ('corporation_id', models.IntegerField(default=0, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('state', models.CharField(default='Open', max_length=32)),
                ('user', models.ForeignKey(blank=True, help_text='The user to whom this transaction belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporation_id', models.BigIntegerField(default=0)),
                ('alliance_id', models.IntegerField(null=True)),
                ('name', models.CharField(default='Cool Corp', max_length=32, null=True)),
                ('ceo_id', models.IntegerField()),
                ('ticker', models.CharField(default='YETI', max_length=24)),
                ('member_count', models.IntegerField()),
                ('last_esi_pull', models.DateTimeField(default=mogul_backend.models.one_day_ago)),
                ('user', models.ForeignKey(blank=True, help_text='The user to whom this character belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPreferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True, verbose_name='Section Name')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
                ('raw_value', models.TextField(blank=True, null=True, verbose_name='Raw Value')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mogul_backend.character')),
            ],
        ),
    ]
