# Generated by Django 3.1.7 on 2021-02-25 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0004_effect_longer_name'),
        ('mogul_backend', '0002_auto_20210225_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eveuniverse.evetype'),
        ),
    ]
