# Generated by Django 3.1.7 on 2021-02-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_backend', '0002_auto_20210227_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_corporation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
