# Generated by Django 3.1.8 on 2021-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_backend', '0002_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='character_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='corporation_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journal',
            name='division_id',
            field=models.IntegerField(default=0),
        ),
    ]
