# Generated by Django 3.1.7 on 2021-02-26 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mogul_backend.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mogul_backend', '0003_auto_20210225_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user to whom this transaction belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alliance_id', models.IntegerField(null=True)),
                ('corporation_id', models.IntegerField()),
                ('name', models.CharField(default='Cool Guy', max_length=32)),
                ('last_esi_pull', models.DateTimeField(default=mogul_backend.models.one_day_ago)),
                ('user', models.ForeignKey(blank=True, help_text='The user to whom this character belongs.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
