# Generated by Django 3.1.7 on 2021-02-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_backend', '0003_auto_20210227_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='Open', max_length=32),
        ),
    ]
