# Generated by Django 3.1.8 on 2021-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_backend', '0005_auto_20210412_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='context_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
