# Generated by Django 3.1.7 on 2021-02-28 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveuniverse', '0004_effect_longer_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mogul_backend', '0005_characterpreferencemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='state',
            new_name='processed',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('station', models.BigIntegerField()),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax_data', models.JSONField()),
                ('item', models.ForeignKey(help_text='The item involved on this stock row.', null=True, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evetype')),
                ('transaction', models.ForeignKey(help_text='The transaction that created the stock.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_trans_row', to='mogul_backend.transaction')),
                ('user', models.ForeignKey(help_text='The user to whom this stock belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_data', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('station', models.BigIntegerField()),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax_data', models.JSONField()),
                ('item', models.ForeignKey(help_text='The item involved on this profit row.', null=True, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evetype')),
                ('transaction', models.ForeignKey(help_text='The transaction that created the profit.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_trans_row', to='mogul_backend.transaction')),
                ('user', models.ForeignKey(help_text='The user to whom this profit belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
