# Generated by Django 3.1.7 on 2021-02-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_backend', '0006_auto_20210228_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='unit_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
