# Generated by Django 3.1.7 on 2021-02-26 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_backend', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='character_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 17, 5, 12, 560548, tzinfo=utc), null=True),
        ),
    ]
