# Generated by Django 3.1.7 on 2021-02-26 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_backend', '0007_auto_20210226_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='character_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 20, 49, 24, 509666, tzinfo=utc), null=True),
        ),
    ]
