# Generated by Django 3.1.7 on 2021-02-26 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_backend', '0008_auto_20210226_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown Structure', max_length=32)),
                ('owner_id', models.IntegerField()),
                ('solar_system_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('position_x', models.FloatField(blank=True, default=None, help_text='x position in the solar system', null=True)),
                ('position_y', models.FloatField(blank=True, default=None, help_text='y position in the solar system', null=True)),
                ('position_z', models.FloatField(blank=True, default=None, help_text='z position in the solar system', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
