# Generated by Django 3.1.7 on 2021-02-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_backend', '0009_auto_20210226_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(default='Unknown Structure', max_length=64),
        ),
    ]
