# Generated by Django 3.1.8 on 2021-04-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveuniverse', '0004_effect_longer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrders',
            fields=[
                ('duration', models.IntegerField()),
                ('is_buy_order', models.BooleanField(null=True)),
                ('issued', models.DateTimeField()),
                ('location_id', models.BigIntegerField()),
                ('min_volume', models.IntegerField(default=0, null=True)),
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('range', models.CharField(default='0', max_length=16)),
                ('system_id', models.IntegerField()),
                ('volume_remain', models.IntegerField()),
                ('volume_total', models.IntegerField()),
                ('item', models.ForeignKey(help_text='The item involved on this profit row.', null=True, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evetype')),
            ],
        ),
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField(blank=True, default=None, null=True)),
                ('highest', models.FloatField(blank=True, default=None, null=True)),
                ('lowest', models.FloatField(blank=True, default=None, null=True)),
                ('order_count', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('region_id', models.IntegerField()),
                ('item', models.ForeignKey(help_text='The item involved on this profit row.', null=True, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.evetype')),
            ],
        ),
    ]
