# Generated by Django 3.1.7 on 2021-02-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('is_buy', models.BooleanField(null=True)),
                ('is_personal', models.BooleanField(null=True)),
                ('journal_ref_id', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('transaction_id', models.BigIntegerField()),
                ('type_id', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=24)),
            ],
        ),
    ]
