# Generated by Django 3.1.7 on 2021-02-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_auth', '0002_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
