# Generated by Django 3.1.7 on 2021-02-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogul_auth', '0003_auto_20210224_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
